### ISSUE TITLE
Remove prefixing

### ISSUE THREAD

**Issue by corysimmons** [ConnorAtherton/loaders.css#18]
Everyone could/should be using Autoprefixer (or some similar/lesser tool) in their development environment. It's usually a bad practice to have prefixing in libraries.

**Comment by ConnorAtherton** [comment]
I didn't know it was bad practice. Could you elaborate? 

I don't see the down side including prefixes here. In the case that they don't use autoprefixer (I agree, they should) the styles will work and if they do then it works anyway, no harm done.

**Comment by corysimmons** [comment]
I used to think that way but I got chewed out by the community for doing it and now I'm a convert.

The idea is, it's not Loaders.css' job to prefix. It adds repo bloat for no benefit. I promise you won't have many issues from this change.

**Comment by ConnorAtherton** [comment]
Okay, I can see the sense in that. I've just uncommented it out for now.

**Comment by corysimmons** [comment]
:+1:

**Comment by fricks** [comment]
I dont use autoprefixer and I use SASS. Too bad remove the prefixer :-1:

**Comment by corysimmons** [comment]
You should be using Autoprefixer in your build process though. :\

**Comment by rictorres** [comment]
You are _assuming_ that whoever uses this library **must** have a build process in their project.

Are you sure this is the _correct_ approach?

Also, Autoprefixer will add or remove prefixes according to your settings.

**Comment by corysimmons** [comment]
It's a pretty fair assumption to say that most people will have some sort of build process, and that in that build process they'll be using Autoprefixer.

On the flip side you're assuming they want prefixes baked in - I for one don't. I'd rather have personal control over what prefixes are added with my Autoprefixer settings rather than some heavy handed prefixes applied that may or may not be relevant in a month.

**Comment by rictorres** [comment]
I disagree. Imagine jQuery publishing a ES6-only version hoping that most users are using Babel or similar.

If you're using Autoprefixer, **you* have personal control over the prefixes: it'll add or remove prefixes according to your settings :)

**Comment by corysimmons** [comment]
Ultimately it's up to the maintainer of the lib. I'll personally never prefix a single library I create and continue assuming people are using Autoprefixer, and if they aren't, help them to use it.

@ConnorAtherton Some of your users have expressed concern about this change and I seem to be the only one against it, so maybe it's time to reconsider prefixes.

Here's some further reading about when I used to argue for prefixes and the community asking me to remove them:

- https://github.com/mojotech/jeet/issues/227
- https://github.com/mojotech/jeet/issues/211
- https://github.com/mojotech/jeet/issues/114

Here's typically what happens when someone who isn't using Autoprefixer comes along (pretty rare):

- https://github.com/mojotech/jeet/issues/394

**Comment by ConnorAtherton** [comment]
Thanks for the input guys. I especially appreciate the links @corysimmons.

My original thoughts on this topic can be summed up with [this comment](https://github.com/mojotech/jeet/issues/227#issuecomment-41500565). Apart from the extra bloat, I saw no harm adding prefixes for reasons outlined in that comment. And as @rictorres mentioned earlier, you still have control over which prefixes to keep and which to remove.

It requires extra effort to add a build system to run through Autoprefixer whereas it requires no effort to run it through your current build system because you will have already configured the settings. 

The main argument against adding prefixes by default is that the library would then be making decisions it shouldn't, as well as violating the single responsibility principle. I think that's a fair argument if you assume that most - if not everyone - using the library will be running it through some build step to add the prefixes before using it. From my experience with the node community, this is the case. However, I'm not sure about other other communities out there and I don't want to rule people out from using this just because I assumed they had a particular build step in their system. 

Adding them does add extra bloat but I think in this instance this is justified because the unprefixed [browser support](http://caniuse.com/#search=css-animation) is so low (22.3%). 

For now, I want to keep them in and revisit this in the future when I've asked around a bit more.

**Comment by corysimmons** [comment]
I personally disagree with this decision, but I think it's a really good idea to listen to your users so :+1:

**Comment by rictorres** [comment]
good call, @ConnorAtherton  :+1:

**Comment by fricks** [comment]
Don't worry about me, I just remove the loaders.css from my project :)

**Comment by mustaqsheikh** [comment]
I agree with rictorres.
