### ISSUE TITLE
Build is non-deterministic, CSS changes on every build

### ISSUE THREAD

**Issue by markdalgleish** [ConnorAtherton/loaders.css#37]
The random animation delays (e.g. https://github.com/ConnorAtherton/loaders.css/blob/40dfe696dae81901ec6253ed482c2cd692ff34c1/src/animations/line-scale-random.scss#L20-L21) are only calculated at build time and make the build non-deterministic.

Every build results in a different CSS file, which is probably not ideal for a number of reasons:

 - A refactor with no change to the resulting CSS will still generate new animations.
 - Random animations are locked for each version, so users of an app using this library will see the same "random" animation for a while until they upgrade, at which point they'll get a new "random" animation until the next upgrade.

If you don't see this as a problem, feel free to close this issue.

**Comment by ConnorAtherton** [comment]
Yeah, I'm not entirely happy with this behaviour. It wasn't a big issue for me at the start because I was just having fun with it and seeing what interesting animations I could create under imposed constraints.

I think if the parameters that generate the randomness are bounded in such a way that it doesn't change the output enough for people to visually notice, then I don't see it as a problem. 

However, I've never been entirely comfortable with values changing for no reason just from a maintenance standpoint. I want to keep this open and replace the random calls to verbose `nth-child` declarations. 

p.s. How did you get involved in nodeschool? I would love find a way to help out in my spare time.
