### ISSUE TITLE
Name of the specific loader?

### ISSUE THREAD

**Issue by vchrombie** [ConnorAtherton/loaders.css#83]
How to know the name of the specific loader?
Neither mentioned on the website nor in the README.

It will be good to see the names of the loaders on the website (maybe on hover).
Correct me if I am wrong.

**Comment by ConnorAtherton** [comment]
Sounds like this is a feature request to display the name of each loader alongside the loader itself, which I think is a great idea. I'll do it in the next few days. 

I usually suggest people go to the loader source, for two reasons. First, for most projects loading in this whole project just to select one loader is unnecessary bloat. Second, the only route to customize a loader for your app is by copying and tweaking one, which I don't think is a bad thing, since I originally intended this to be an inspiration of what smooth, fast loaders could be.
